# Generated by Django 4.0.3 on 2022-03-17 08:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_rename_quantity_inventoryitem_quantity_mass_volume_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inventoryitem',
            name='measurement_in',
            field=models.CharField(choices=[('L', 'Liters'), ('ml', 'Milliliters'), ('Kg', 'Kilograms'), ('g', 'Grams'), ('P_', 'Pairs'), ('s', 'Single object(s)'), ('m', 'Meters'), ('ft', 'Feet')], default='s', max_length=50),
        ),
    ]
