# Generated by Django 4.0.3 on 2022-03-17 08:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_alter_inventoryitem_measurement_in'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inventoryitem',
            name='measurement_in',
            field=models.CharField(choices=[('L', 'Liters'), ('ml', 'Milliliters'), ('Kg', 'Kilograms'), ('g', 'Grams'), ('P_', 'Pairs'), ('m', 'Meters'), ('ft', 'Feet'), ('s', 'Single object(s)')], default='s', max_length=50),
        ),
    ]
