# Generated by Django 4.0.3 on 2022-03-17 09:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_alter_inventoryitem_measurement_in'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inventoryitem',
            name='condition',
            field=models.CharField(choices=[('Excellent', 'Excellent'), ('Good', 'Good'), ('Average', 'Average'), ('Bad', 'Bad'), ('Poor', 'Poor')], default='Average', max_length=50),
        ),
        migrations.AlterField(
            model_name='inventoryitem',
            name='measurement_in',
            field=models.CharField(choices=[('Liters (L)', 'Liters'), ('Milliliters (ml)', 'Milliliters'), ('Kilograms (Kg)', 'Kilograms'), ('Grams (g)', 'Grams'), ('Pairs (P_)', 'Pairs'), ('Meters (m)', 'Meters'), ('Feet (ft)', 'Feet'), ('Singel Object[s] (s)', 'Single object(s)')], default='Singel Object[s] (s)', max_length=50),
        ),
    ]
