# Generated by Django 4.0.3 on 2022-03-17 09:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_alter_inventoryitem_condition_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inventoryitem',
            name='measurement_in',
            field=models.CharField(choices=[('Liters (L)', 'Liters'), ('Milliliters (ml)', 'Milliliters'), ('Kilograms (Kg)', 'Kilograms'), ('Grams (g)', 'Grams'), ('Pairs (P_)', 'Pairs'), ('Meters (m)', 'Meters'), ('Feet (ft)', 'Feet'), ('Singel Object(s)', 'Single object(s)')], default='Singel Object(s)', max_length=50),
        ),
    ]
