# Generated by Django 4.0.3 on 2022-03-17 09:53

from django.db import migrations
import slugger.fields


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_alter_inventoryitem_measurement_in'),
    ]

    operations = [
        migrations.AddField(
            model_name='inventoryitem',
            name='slug',
            field=slugger.fields.AutoSlugField(default=1, populate_from='name'),
            preserve_default=False,
        ),
    ]
