# Generated by Django 4.0.3 on 2022-03-19 08:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_inventoryitem_slug'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='inventoryitem',
            name='slug',
        ),
        migrations.AlterField(
            model_name='inventoryitem',
            name='category',
            field=models.CharField(choices=[('Plumbing', 'Plumbing'), ('Construction', 'Construction'), ('Animal', 'Animal'), ('Farm', 'Farm'), ('Indoor', 'Indoor'), ('Miscellenious', 'Miscellenious')], max_length=50),
        ),
        migrations.AlterField(
            model_name='inventoryitem',
            name='location',
            field=models.CharField(choices=[('East Wing Store', 'East Wing Store'), ('West Wing Store', 'West Wing Store')], max_length=50),
        ),
        migrations.DeleteModel(
            name='Category',
        ),
        migrations.DeleteModel(
            name='Location',
        ),
    ]
